#Email already exists
POST http://localhost:5000/auth/signup
content-type: application/json

{
  "name": "Diego",
  "email": "diegodofuturo1@gmail.com",
  "password": "xxxx"
}

###Create Email
POST http://localhost:5000/auth/signup
content-type: application/json

{
  "email": "teste1@gmail.com",
  "password": "123456"
}